name: Build Keyboard Tester App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. Get the code
      uses: actions/checkout@v4

    - name: 2. Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: 3. Compile and Link the program
      run: cl /utf-8 main.cpp /Fe:keyboard-tester.exe /link user32.lib /ENTRY:wWinMainCRTStartup

    - name: 4. Upload the professional executable
      uses: actions/upload-artifact@v4
      with:
        # اسم جديد احترافي للملف
        name: Keyboard-Tester-App
        path: keyboard-tester.exe
