name: Web-Based Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # تم التحديث إلى v4
    - uses: actions/checkout@v4

    - name: Compile C++ program
      run: g++ main.cpp -o my-program

    # تم التحديث إلى v4
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Web-Built-Executable
        path: my-program
